server:
  port: 8082

spring:
  application:
    name: customer-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/bank_management?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8085