server:
  port: 8999

#eureka:
#  instance:
#    hostname: localhost

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-management-service
          uri: lb://customer-management-service
          predicates:
            - Path=/customer/profile/**

        - id: account-management-service
          uri: lb://account-management-service
          predicates:
            - Path=/account/profile/**